// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spkvpenergy/service/energy.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringRequest) Reset()         { *m = StringRequest{} }
func (m *StringRequest) String() string { return proto.CompactTextString(m) }
func (*StringRequest) ProtoMessage()    {}
func (*StringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{0}
}

func (m *StringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringRequest.Unmarshal(m, b)
}
func (m *StringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringRequest.Marshal(b, m, deterministic)
}
func (m *StringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringRequest.Merge(m, src)
}
func (m *StringRequest) XXX_Size() int {
	return xxx_messageInfo_StringRequest.Size(m)
}
func (m *StringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StringRequest proto.InternalMessageInfo

func (m *StringRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StringResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringResponse) Reset()         { *m = StringResponse{} }
func (m *StringResponse) String() string { return proto.CompactTextString(m) }
func (*StringResponse) ProtoMessage()    {}
func (*StringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{1}
}

func (m *StringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringResponse.Unmarshal(m, b)
}
func (m *StringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringResponse.Marshal(b, m, deterministic)
}
func (m *StringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringResponse.Merge(m, src)
}
func (m *StringResponse) XXX_Size() int {
	return xxx_messageInfo_StringResponse.Size(m)
}
func (m *StringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StringResponse proto.InternalMessageInfo

func (m *StringResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChartDataRequest struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Step                 int64    `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChartDataRequest) Reset()         { *m = ChartDataRequest{} }
func (m *ChartDataRequest) String() string { return proto.CompactTextString(m) }
func (*ChartDataRequest) ProtoMessage()    {}
func (*ChartDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{2}
}

func (m *ChartDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDataRequest.Unmarshal(m, b)
}
func (m *ChartDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDataRequest.Marshal(b, m, deterministic)
}
func (m *ChartDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDataRequest.Merge(m, src)
}
func (m *ChartDataRequest) XXX_Size() int {
	return xxx_messageInfo_ChartDataRequest.Size(m)
}
func (m *ChartDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDataRequest proto.InternalMessageInfo

func (m *ChartDataRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ChartDataRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *ChartDataRequest) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

type ChartDataResponse struct {
	Series               []*ChartSeriesData `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChartDataResponse) Reset()         { *m = ChartDataResponse{} }
func (m *ChartDataResponse) String() string { return proto.CompactTextString(m) }
func (*ChartDataResponse) ProtoMessage()    {}
func (*ChartDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{3}
}

func (m *ChartDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDataResponse.Unmarshal(m, b)
}
func (m *ChartDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDataResponse.Marshal(b, m, deterministic)
}
func (m *ChartDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDataResponse.Merge(m, src)
}
func (m *ChartDataResponse) XXX_Size() int {
	return xxx_messageInfo_ChartDataResponse.Size(m)
}
func (m *ChartDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDataResponse proto.InternalMessageInfo

func (m *ChartDataResponse) GetSeries() []*ChartSeriesData {
	if m != nil {
		return m.Series
	}
	return nil
}

type ChartSeriesData struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values               []*SeriesValues `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChartSeriesData) Reset()         { *m = ChartSeriesData{} }
func (m *ChartSeriesData) String() string { return proto.CompactTextString(m) }
func (*ChartSeriesData) ProtoMessage()    {}
func (*ChartSeriesData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{4}
}

func (m *ChartSeriesData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartSeriesData.Unmarshal(m, b)
}
func (m *ChartSeriesData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartSeriesData.Marshal(b, m, deterministic)
}
func (m *ChartSeriesData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartSeriesData.Merge(m, src)
}
func (m *ChartSeriesData) XXX_Size() int {
	return xxx_messageInfo_ChartSeriesData.Size(m)
}
func (m *ChartSeriesData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartSeriesData.DiscardUnknown(m)
}

var xxx_messageInfo_ChartSeriesData proto.InternalMessageInfo

func (m *ChartSeriesData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChartSeriesData) GetValues() []*SeriesValues {
	if m != nil {
		return m.Values
	}
	return nil
}

type SeriesValues struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeriesValues) Reset()         { *m = SeriesValues{} }
func (m *SeriesValues) String() string { return proto.CompactTextString(m) }
func (*SeriesValues) ProtoMessage()    {}
func (*SeriesValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{5}
}

func (m *SeriesValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeriesValues.Unmarshal(m, b)
}
func (m *SeriesValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeriesValues.Marshal(b, m, deterministic)
}
func (m *SeriesValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeriesValues.Merge(m, src)
}
func (m *SeriesValues) XXX_Size() int {
	return xxx_messageInfo_SeriesValues.Size(m)
}
func (m *SeriesValues) XXX_DiscardUnknown() {
	xxx_messageInfo_SeriesValues.DiscardUnknown(m)
}

var xxx_messageInfo_SeriesValues proto.InternalMessageInfo

func (m *SeriesValues) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SeriesValues) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type EventsRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Forward              int64    `protobuf:"varint,2,opt,name=forward,proto3" json:"forward,omitempty"`
	Backward             int64    `protobuf:"varint,3,opt,name=backward,proto3" json:"backward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsRequest) Reset()         { *m = EventsRequest{} }
func (m *EventsRequest) String() string { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()    {}
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{6}
}

func (m *EventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsRequest.Unmarshal(m, b)
}
func (m *EventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsRequest.Marshal(b, m, deterministic)
}
func (m *EventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequest.Merge(m, src)
}
func (m *EventsRequest) XXX_Size() int {
	return xxx_messageInfo_EventsRequest.Size(m)
}
func (m *EventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequest proto.InternalMessageInfo

func (m *EventsRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *EventsRequest) GetForward() int64 {
	if m != nil {
		return m.Forward
	}
	return 0
}

func (m *EventsRequest) GetBackward() int64 {
	if m != nil {
		return m.Backward
	}
	return 0
}

type EventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	LastDate             int64    `protobuf:"varint,2,opt,name=lastDate,proto3" json:"lastDate,omitempty"`
	FirstDate            int64    `protobuf:"varint,3,opt,name=firstDate,proto3" json:"firstDate,omitempty"`
	HaveMore             bool     `protobuf:"varint,4,opt,name=haveMore,proto3" json:"haveMore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsResponse) Reset()         { *m = EventsResponse{} }
func (m *EventsResponse) String() string { return proto.CompactTextString(m) }
func (*EventsResponse) ProtoMessage()    {}
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{7}
}

func (m *EventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsResponse.Unmarshal(m, b)
}
func (m *EventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsResponse.Marshal(b, m, deterministic)
}
func (m *EventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse.Merge(m, src)
}
func (m *EventsResponse) XXX_Size() int {
	return xxx_messageInfo_EventsResponse.Size(m)
}
func (m *EventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse proto.InternalMessageInfo

func (m *EventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *EventsResponse) GetLastDate() int64 {
	if m != nil {
		return m.LastDate
	}
	return 0
}

func (m *EventsResponse) GetFirstDate() int64 {
	if m != nil {
		return m.FirstDate
	}
	return 0
}

func (m *EventsResponse) GetHaveMore() bool {
	if m != nil {
		return m.HaveMore
	}
	return false
}

type Event struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Params               string   `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{8}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Event) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

type LastDataResponse struct {
	LastData             []*LastData `protobuf:"bytes,1,rep,name=lastData,proto3" json:"lastData,omitempty"`
	DataTime             int64       `protobuf:"varint,2,opt,name=dataTime,proto3" json:"dataTime,omitempty"`
	Online               bool        `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Alarm                bool        `protobuf:"varint,4,opt,name=alarm,proto3" json:"alarm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LastDataResponse) Reset()         { *m = LastDataResponse{} }
func (m *LastDataResponse) String() string { return proto.CompactTextString(m) }
func (*LastDataResponse) ProtoMessage()    {}
func (*LastDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{9}
}

func (m *LastDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastDataResponse.Unmarshal(m, b)
}
func (m *LastDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastDataResponse.Marshal(b, m, deterministic)
}
func (m *LastDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastDataResponse.Merge(m, src)
}
func (m *LastDataResponse) XXX_Size() int {
	return xxx_messageInfo_LastDataResponse.Size(m)
}
func (m *LastDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastDataResponse proto.InternalMessageInfo

func (m *LastDataResponse) GetLastData() []*LastData {
	if m != nil {
		return m.LastData
	}
	return nil
}

func (m *LastDataResponse) GetDataTime() int64 {
	if m != nil {
		return m.DataTime
	}
	return 0
}

func (m *LastDataResponse) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *LastDataResponse) GetAlarm() bool {
	if m != nil {
		return m.Alarm
	}
	return false
}

type LastData struct {
	ParamName            string   `protobuf:"bytes,1,opt,name=paramName,proto3" json:"paramName,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastData) Reset()         { *m = LastData{} }
func (m *LastData) String() string { return proto.CompactTextString(m) }
func (*LastData) ProtoMessage()    {}
func (*LastData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ba2a1a88e0704b6, []int{10}
}

func (m *LastData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastData.Unmarshal(m, b)
}
func (m *LastData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastData.Marshal(b, m, deterministic)
}
func (m *LastData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastData.Merge(m, src)
}
func (m *LastData) XXX_Size() int {
	return xxx_messageInfo_LastData.Size(m)
}
func (m *LastData) XXX_DiscardUnknown() {
	xxx_messageInfo_LastData.DiscardUnknown(m)
}

var xxx_messageInfo_LastData proto.InternalMessageInfo

func (m *LastData) GetParamName() string {
	if m != nil {
		return m.ParamName
	}
	return ""
}

func (m *LastData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*StringRequest)(nil), "service.StringRequest")
	proto.RegisterType((*StringResponse)(nil), "service.StringResponse")
	proto.RegisterType((*ChartDataRequest)(nil), "service.ChartDataRequest")
	proto.RegisterType((*ChartDataResponse)(nil), "service.ChartDataResponse")
	proto.RegisterType((*ChartSeriesData)(nil), "service.ChartSeriesData")
	proto.RegisterType((*SeriesValues)(nil), "service.SeriesValues")
	proto.RegisterType((*EventsRequest)(nil), "service.EventsRequest")
	proto.RegisterType((*EventsResponse)(nil), "service.EventsResponse")
	proto.RegisterType((*Event)(nil), "service.Event")
	proto.RegisterType((*LastDataResponse)(nil), "service.LastDataResponse")
	proto.RegisterType((*LastData)(nil), "service.LastData")
}

func init() { proto.RegisterFile("spkvpenergy/service/energy.proto", fileDescriptor_8ba2a1a88e0704b6) }

var fileDescriptor_8ba2a1a88e0704b6 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6f, 0x13, 0x3f,
	0x10, 0x95, 0x93, 0x74, 0x9b, 0xcc, 0xaf, 0xcd, 0x2f, 0x35, 0xb4, 0x6c, 0x23, 0x0e, 0xd1, 0x1e,
	0x50, 0xa8, 0xd4, 0xb4, 0x2a, 0x07, 0xc4, 0x05, 0xa4, 0x42, 0x6e, 0x50, 0x21, 0xb7, 0xe2, 0x40,
	0x4f, 0x6e, 0xea, 0xa6, 0xab, 0x26, 0xde, 0xc5, 0x76, 0x42, 0x73, 0xe4, 0x8c, 0xc4, 0xdf, 0x8c,
	0x3c, 0xfe, 0xd8, 0xed, 0x07, 0x48, 0xdc, 0xf6, 0xcd, 0x8c, 0xdf, 0xf8, 0x3d, 0xcf, 0x2c, 0x0c,
	0x74, 0x79, 0xb3, 0x2c, 0x85, 0x14, 0x6a, 0xba, 0x3a, 0xd0, 0x42, 0x2d, 0xf3, 0x89, 0x38, 0x70,
	0x70, 0x54, 0xaa, 0xc2, 0x14, 0x74, 0xdd, 0x47, 0xb3, 0x97, 0xb0, 0x79, 0x6a, 0x54, 0x2e, 0xa7,
	0x4c, 0x7c, 0x5b, 0x08, 0x6d, 0x68, 0x0a, 0xeb, 0x73, 0xa1, 0x35, 0x9f, 0x8a, 0x94, 0x0c, 0xc8,
	0xb0, 0xc3, 0x02, 0xcc, 0xf6, 0xa0, 0x1b, 0x4a, 0x75, 0x59, 0x48, 0x2d, 0xfe, 0x52, 0x7b, 0x02,
	0xbd, 0xf7, 0xd7, 0x5c, 0x99, 0x0f, 0xdc, 0xf0, 0xc0, 0xfc, 0x14, 0xd6, 0xb4, 0xe1, 0xca, 0x60,
	0x6d, 0x93, 0x39, 0x40, 0x7b, 0xd0, 0x14, 0xf2, 0x32, 0x6d, 0x60, 0xcc, 0x7e, 0x52, 0x0a, 0x2d,
	0x6d, 0x44, 0x99, 0x36, 0x31, 0x84, 0xdf, 0xd9, 0x18, 0xb6, 0x6a, 0x7c, 0xbe, 0xfd, 0x21, 0x24,
	0x5a, 0xa8, 0x5c, 0xe8, 0x94, 0x0c, 0x9a, 0xc3, 0xff, 0x8e, 0xd2, 0x91, 0x57, 0x35, 0xc2, 0xda,
	0x53, 0xcc, 0xe1, 0x09, 0x5f, 0x97, 0x9d, 0xc1, 0xff, 0xf7, 0x52, 0xb6, 0x9b, 0xe4, 0xf3, 0x20,
	0x00, 0xbf, 0xe9, 0x3e, 0x24, 0x4b, 0x3e, 0x5b, 0x08, 0x9d, 0x36, 0x90, 0x78, 0x3b, 0x12, 0xbb,
	0x83, 0x5f, 0x30, 0xc9, 0x7c, 0x51, 0xb6, 0x07, 0x1b, 0xf5, 0x38, 0xdd, 0x00, 0x72, 0xeb, 0x45,
	0x92, 0x5b, 0x8b, 0x56, 0x28, 0x8f, 0x30, 0xb2, 0xca, 0xce, 0x61, 0x73, 0xbc, 0x14, 0xd2, 0xe8,
	0x9a, 0x2b, 0x93, 0x62, 0x21, 0xa3, 0x2b, 0x08, 0xac, 0xb3, 0x57, 0x85, 0xfa, 0xce, 0x55, 0x70,
	0x26, 0x40, 0xda, 0x87, 0xf6, 0x05, 0x9f, 0xdc, 0x60, 0xca, 0x39, 0x14, 0x71, 0xf6, 0x8b, 0x40,
	0x37, 0xb0, 0x7b, 0x8f, 0x5e, 0x40, 0xe2, 0x22, 0xde, 0xa3, 0x6e, 0x94, 0x82, 0x61, 0xe6, 0xb3,
	0x96, 0x76, 0xc6, 0xb5, 0xf5, 0x57, 0xf8, 0x8e, 0x11, 0xd3, 0xe7, 0xd0, 0xb9, 0xca, 0x95, 0x4f,
	0xba, 0x9e, 0x55, 0xc0, 0x9e, 0xbc, 0xe6, 0x4b, 0xf1, 0xa9, 0x50, 0x22, 0x6d, 0x0d, 0xc8, 0xb0,
	0xcd, 0x22, 0xce, 0xce, 0x61, 0x0d, 0xf9, 0xff, 0xe5, 0xed, 0xf1, 0x35, 0x9a, 0xb5, 0xd7, 0xd8,
	0x81, 0xa4, 0xe4, 0x8a, 0xcf, 0x35, 0xd2, 0x77, 0x98, 0x47, 0xd9, 0x4f, 0x02, 0xbd, 0x8f, 0xee,
	0x8e, 0xd5, 0x4c, 0xec, 0x47, 0x1d, 0xdc, 0x2b, 0xde, 0x8a, 0x8a, 0x63, 0x71, 0x2c, 0xb1, 0x97,
	0xbf, 0xe4, 0x86, 0x9f, 0xe5, 0xf3, 0x28, 0x3b, 0x60, 0xdb, 0xb7, 0x90, 0xb3, 0x5c, 0xba, 0xdb,
	0xb4, 0x99, 0x47, 0x56, 0x0b, 0x9f, 0x71, 0x35, 0xf7, 0x6a, 0x1d, 0xc8, 0xde, 0x42, 0x3b, 0xf0,
	0x5b, 0xc3, 0xf0, 0x8e, 0x27, 0xd5, 0x60, 0x55, 0x01, 0x7b, 0x1e, 0x07, 0x07, 0x1b, 0x76, 0x98,
	0x03, 0x47, 0x3f, 0x1a, 0x90, 0x8c, 0x71, 0x45, 0xe9, 0x6b, 0x68, 0x7d, 0xce, 0xe5, 0x94, 0xee,
	0x54, 0x63, 0x57, 0x5f, 0xd1, 0xfe, 0xb3, 0x07, 0x71, 0x2f, 0xfe, 0x18, 0x3a, 0x71, 0x4b, 0xe8,
	0xee, 0xdd, 0x6d, 0xa8, 0x6d, 0x62, 0xbf, 0xff, 0x58, 0xca, 0x73, 0xbc, 0x09, 0x03, 0x53, 0x6b,
	0x7f, 0x67, 0x62, 0x6b, 0xed, 0xef, 0xcd, 0xda, 0xbb, 0x9a, 0x05, 0x7f, 0xba, 0xfb, 0xee, 0xc3,
	0xd7, 0xf0, 0xc7, 0x0f, 0xc9, 0xf1, 0xf6, 0xd7, 0x27, 0x8f, 0xfc, 0xb9, 0x2e, 0x12, 0xfc, 0x67,
	0xbd, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x11, 0x42, 0x43, 0xd6, 0xd7, 0x04, 0x00, 0x00,
}
