// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthResp auth resp
// Example: {"name":"name","token":"token"}
//
// swagger:model authResp
type AuthResp struct {

	// name
	Name string `json:"name,omitempty"`

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this auth resp
func (m *AuthResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth resp based on context it is used
func (m *AuthResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthResp) UnmarshalBinary(b []byte) error {
	var res AuthResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
