// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EventParamValue event param value
// swagger:model eventParamValue
type EventParamValue struct {

	// f
	F string `json:"f,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// v
	V string `json:"v,omitempty"`
}

// Validate validates this event param value
func (m *EventParamValue) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventParamValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventParamValue) UnmarshalBinary(b []byte) error {
	var res EventParamValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
