// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EventsListByDeviceReq events list by device req
// swagger:model eventsListByDeviceReq
type EventsListByDeviceReq struct {

	// device ids
	DeviceIds []int64 `json:"device_ids"`

	// is active
	IsActive *int64 `json:"is_active,omitempty"`

	// is critical
	IsCritical *int64 `json:"is_critical,omitempty"`

	// status
	Status *int64 `json:"status,omitempty"`
}

// Validate validates this events list by device req
func (m *EventsListByDeviceReq) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventsListByDeviceReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventsListByDeviceReq) UnmarshalBinary(b []byte) error {
	var res EventsListByDeviceReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
