// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Measurement measurement
//
// swagger:model measurement
type Measurement struct {

	// default precision
	DefaultPrecision int32 `json:"default_precision,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// visible
	Visible int32 `json:"visible,omitempty"`
}

// Validate validates this measurement
func (m *Measurement) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this measurement based on context it is used
func (m *Measurement) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Measurement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Measurement) UnmarshalBinary(b []byte) error {
	var res Measurement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
