// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ParameterDataValue parameter data value
// swagger:model parameterDataValue
type ParameterDataValue struct {

	// d
	D int64 `json:"d,omitempty"`

	// e
	E string `json:"e,omitempty"`

	// f
	F string `json:"f,omitempty"`

	// v
	V string `json:"v,omitempty"`
}

// Validate validates this parameter data value
func (m *ParameterDataValue) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParameterDataValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParameterDataValue) UnmarshalBinary(b []byte) error {
	var res ParameterDataValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
