// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeviceTypesInfoParams creates a new DeviceTypesInfoParams object
// with the default values initialized.
func NewDeviceTypesInfoParams() *DeviceTypesInfoParams {
	var ()
	return &DeviceTypesInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeviceTypesInfoParamsWithTimeout creates a new DeviceTypesInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeviceTypesInfoParamsWithTimeout(timeout time.Duration) *DeviceTypesInfoParams {
	var ()
	return &DeviceTypesInfoParams{

		timeout: timeout,
	}
}

// NewDeviceTypesInfoParamsWithContext creates a new DeviceTypesInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeviceTypesInfoParamsWithContext(ctx context.Context) *DeviceTypesInfoParams {
	var ()
	return &DeviceTypesInfoParams{

		Context: ctx,
	}
}

// NewDeviceTypesInfoParamsWithHTTPClient creates a new DeviceTypesInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeviceTypesInfoParamsWithHTTPClient(client *http.Client) *DeviceTypesInfoParams {
	var ()
	return &DeviceTypesInfoParams{
		HTTPClient: client,
	}
}

/*DeviceTypesInfoParams contains all the parameters to send to the API endpoint
for the device types info operation typically these are written to a http.Request
*/
type DeviceTypesInfoParams struct {

	/*Body*/
	Body []int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the device types info params
func (o *DeviceTypesInfoParams) WithTimeout(timeout time.Duration) *DeviceTypesInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the device types info params
func (o *DeviceTypesInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the device types info params
func (o *DeviceTypesInfoParams) WithContext(ctx context.Context) *DeviceTypesInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the device types info params
func (o *DeviceTypesInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the device types info params
func (o *DeviceTypesInfoParams) WithHTTPClient(client *http.Client) *DeviceTypesInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the device types info params
func (o *DeviceTypesInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the device types info params
func (o *DeviceTypesInfoParams) WithBody(body []int64) *DeviceTypesInfoParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the device types info params
func (o *DeviceTypesInfoParams) SetBody(body []int64) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeviceTypesInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
