// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEventListParams creates a new EventListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEventListParams() *EventListParams {
	return &EventListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEventListParamsWithTimeout creates a new EventListParams object
// with the ability to set a timeout on a request.
func NewEventListParamsWithTimeout(timeout time.Duration) *EventListParams {
	return &EventListParams{
		timeout: timeout,
	}
}

// NewEventListParamsWithContext creates a new EventListParams object
// with the ability to set a context for a request.
func NewEventListParamsWithContext(ctx context.Context) *EventListParams {
	return &EventListParams{
		Context: ctx,
	}
}

// NewEventListParamsWithHTTPClient creates a new EventListParams object
// with the ability to set a custom HTTPClient for a request.
func NewEventListParamsWithHTTPClient(client *http.Client) *EventListParams {
	return &EventListParams{
		HTTPClient: client,
	}
}

/* EventListParams contains all the parameters to send to the API endpoint
   for the event list operation.

   Typically these are written to a http.Request.
*/
type EventListParams struct {

	/* Body.

	   Parameters
	*/
	Body EventListBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the event list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventListParams) WithDefaults() *EventListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the event list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the event list params
func (o *EventListParams) WithTimeout(timeout time.Duration) *EventListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the event list params
func (o *EventListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the event list params
func (o *EventListParams) WithContext(ctx context.Context) *EventListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the event list params
func (o *EventListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the event list params
func (o *EventListParams) WithHTTPClient(client *http.Client) *EventListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the event list params
func (o *EventListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the event list params
func (o *EventListParams) WithBody(body EventListBody) *EventListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the event list params
func (o *EventListParams) SetBody(body EventListBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EventListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
