// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"spkvpenergy/ocapi/models"
)

// NewEventLogForwardParams creates a new EventLogForwardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEventLogForwardParams() *EventLogForwardParams {
	return &EventLogForwardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEventLogForwardParamsWithTimeout creates a new EventLogForwardParams object
// with the ability to set a timeout on a request.
func NewEventLogForwardParamsWithTimeout(timeout time.Duration) *EventLogForwardParams {
	return &EventLogForwardParams{
		timeout: timeout,
	}
}

// NewEventLogForwardParamsWithContext creates a new EventLogForwardParams object
// with the ability to set a context for a request.
func NewEventLogForwardParamsWithContext(ctx context.Context) *EventLogForwardParams {
	return &EventLogForwardParams{
		Context: ctx,
	}
}

// NewEventLogForwardParamsWithHTTPClient creates a new EventLogForwardParams object
// with the ability to set a custom HTTPClient for a request.
func NewEventLogForwardParamsWithHTTPClient(client *http.Client) *EventLogForwardParams {
	return &EventLogForwardParams{
		HTTPClient: client,
	}
}

/* EventLogForwardParams contains all the parameters to send to the API endpoint
   for the event log forward operation.

   Typically these are written to a http.Request.
*/
type EventLogForwardParams struct {

	// Body.
	Body *models.EventLogForwardReq

	/* ID.

	   DeviceID for fetch

	   Format: int32
	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the event log forward params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventLogForwardParams) WithDefaults() *EventLogForwardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the event log forward params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventLogForwardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the event log forward params
func (o *EventLogForwardParams) WithTimeout(timeout time.Duration) *EventLogForwardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the event log forward params
func (o *EventLogForwardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the event log forward params
func (o *EventLogForwardParams) WithContext(ctx context.Context) *EventLogForwardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the event log forward params
func (o *EventLogForwardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the event log forward params
func (o *EventLogForwardParams) WithHTTPClient(client *http.Client) *EventLogForwardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the event log forward params
func (o *EventLogForwardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the event log forward params
func (o *EventLogForwardParams) WithBody(body *models.EventLogForwardReq) *EventLogForwardParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the event log forward params
func (o *EventLogForwardParams) SetBody(body *models.EventLogForwardReq) {
	o.Body = body
}

// WithID adds the id to the event log forward params
func (o *EventLogForwardParams) WithID(id int32) *EventLogForwardParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the event log forward params
func (o *EventLogForwardParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EventLogForwardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
