// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"spkvpenergy/ocapi/models"
)

// NewEventListByDeviceParams creates a new EventListByDeviceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEventListByDeviceParams() *EventListByDeviceParams {
	return &EventListByDeviceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEventListByDeviceParamsWithTimeout creates a new EventListByDeviceParams object
// with the ability to set a timeout on a request.
func NewEventListByDeviceParamsWithTimeout(timeout time.Duration) *EventListByDeviceParams {
	return &EventListByDeviceParams{
		timeout: timeout,
	}
}

// NewEventListByDeviceParamsWithContext creates a new EventListByDeviceParams object
// with the ability to set a context for a request.
func NewEventListByDeviceParamsWithContext(ctx context.Context) *EventListByDeviceParams {
	return &EventListByDeviceParams{
		Context: ctx,
	}
}

// NewEventListByDeviceParamsWithHTTPClient creates a new EventListByDeviceParams object
// with the ability to set a custom HTTPClient for a request.
func NewEventListByDeviceParamsWithHTTPClient(client *http.Client) *EventListByDeviceParams {
	return &EventListByDeviceParams{
		HTTPClient: client,
	}
}

/* EventListByDeviceParams contains all the parameters to send to the API endpoint
   for the event list by device operation.

   Typically these are written to a http.Request.
*/
type EventListByDeviceParams struct {

	/* Body.

	   Parameters
	*/
	Body *models.EventsListByDeviceReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the event list by device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventListByDeviceParams) WithDefaults() *EventListByDeviceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the event list by device params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EventListByDeviceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the event list by device params
func (o *EventListByDeviceParams) WithTimeout(timeout time.Duration) *EventListByDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the event list by device params
func (o *EventListByDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the event list by device params
func (o *EventListByDeviceParams) WithContext(ctx context.Context) *EventListByDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the event list by device params
func (o *EventListByDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the event list by device params
func (o *EventListByDeviceParams) WithHTTPClient(client *http.Client) *EventListByDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the event list by device params
func (o *EventListByDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the event list by device params
func (o *EventListByDeviceParams) WithBody(body *models.EventsListByDeviceReq) *EventListByDeviceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the event list by device params
func (o *EventListByDeviceParams) SetBody(body *models.EventsListByDeviceReq) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EventListByDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
