// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "spkvpenergy/ocapi/models"
)

// EventLogBackwardReader is a Reader for the EventLogBackward structure.
type EventLogBackwardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EventLogBackwardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEventLogBackwardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEventLogBackwardDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEventLogBackwardOK creates a EventLogBackwardOK with default headers values
func NewEventLogBackwardOK() *EventLogBackwardOK {
	return &EventLogBackwardOK{}
}

/*EventLogBackwardOK handles this case with default header values.

Events for all company devices
*/
type EventLogBackwardOK struct {
	Payload models.EventLogResp
}

func (o *EventLogBackwardOK) Error() string {
	return fmt.Sprintf("[POST /device/events-log-backward/{id}][%d] eventLogBackwardOK  %+v", 200, o.Payload)
}

func (o *EventLogBackwardOK) GetPayload() models.EventLogResp {
	return o.Payload
}

func (o *EventLogBackwardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEventLogBackwardDefault creates a EventLogBackwardDefault with default headers values
func NewEventLogBackwardDefault(code int) *EventLogBackwardDefault {
	return &EventLogBackwardDefault{
		_statusCode: code,
	}
}

/*EventLogBackwardDefault handles this case with default header values.

unexpected error
*/
type EventLogBackwardDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the event log backward default response
func (o *EventLogBackwardDefault) Code() int {
	return o._statusCode
}

func (o *EventLogBackwardDefault) Error() string {
	return fmt.Sprintf("[POST /device/events-log-backward/{id}][%d] eventLogBackward default  %+v", o._statusCode, o.Payload)
}

func (o *EventLogBackwardDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *EventLogBackwardDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
