// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "spkvpenergy/ocapi/models"
)

// NewEventLogParams creates a new EventLogParams object
// with the default values initialized.
func NewEventLogParams() *EventLogParams {
	var ()
	return &EventLogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEventLogParamsWithTimeout creates a new EventLogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEventLogParamsWithTimeout(timeout time.Duration) *EventLogParams {
	var ()
	return &EventLogParams{

		timeout: timeout,
	}
}

// NewEventLogParamsWithContext creates a new EventLogParams object
// with the default values initialized, and the ability to set a context for a request
func NewEventLogParamsWithContext(ctx context.Context) *EventLogParams {
	var ()
	return &EventLogParams{

		Context: ctx,
	}
}

// NewEventLogParamsWithHTTPClient creates a new EventLogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEventLogParamsWithHTTPClient(client *http.Client) *EventLogParams {
	var ()
	return &EventLogParams{
		HTTPClient: client,
	}
}

/*EventLogParams contains all the parameters to send to the API endpoint
for the event log operation typically these are written to a http.Request
*/
type EventLogParams struct {

	/*Body*/
	Body *models.EventLogReq
	/*ID
	  DeviceID for fetch

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the event log params
func (o *EventLogParams) WithTimeout(timeout time.Duration) *EventLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the event log params
func (o *EventLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the event log params
func (o *EventLogParams) WithContext(ctx context.Context) *EventLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the event log params
func (o *EventLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the event log params
func (o *EventLogParams) WithHTTPClient(client *http.Client) *EventLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the event log params
func (o *EventLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the event log params
func (o *EventLogParams) WithBody(body *models.EventLogReq) *EventLogParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the event log params
func (o *EventLogParams) SetBody(body *models.EventLogReq) {
	o.Body = body
}

// WithID adds the id to the event log params
func (o *EventLogParams) WithID(id int32) *EventLogParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the event log params
func (o *EventLogParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EventLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
