// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"spkvpenergy/ocapi/models"
)

// EventLogForwardReader is a Reader for the EventLogForward structure.
type EventLogForwardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EventLogForwardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEventLogForwardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewEventLogForwardDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEventLogForwardOK creates a EventLogForwardOK with default headers values
func NewEventLogForwardOK() *EventLogForwardOK {
	return &EventLogForwardOK{}
}

/* EventLogForwardOK describes a response with status code 200, with default header values.

Events for all company devices
*/
type EventLogForwardOK struct {
	Payload models.EventLogResp
}

func (o *EventLogForwardOK) Error() string {
	return fmt.Sprintf("[POST /device/events-log-forward/{id}][%d] eventLogForwardOK  %+v", 200, o.Payload)
}
func (o *EventLogForwardOK) GetPayload() models.EventLogResp {
	return o.Payload
}

func (o *EventLogForwardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEventLogForwardDefault creates a EventLogForwardDefault with default headers values
func NewEventLogForwardDefault(code int) *EventLogForwardDefault {
	return &EventLogForwardDefault{
		_statusCode: code,
	}
}

/* EventLogForwardDefault describes a response with status code -1, with default header values.

unexpected error
*/
type EventLogForwardDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the event log forward default response
func (o *EventLogForwardDefault) Code() int {
	return o._statusCode
}

func (o *EventLogForwardDefault) Error() string {
	return fmt.Sprintf("[POST /device/events-log-forward/{id}][%d] eventLogForward default  %+v", o._statusCode, o.Payload)
}
func (o *EventLogForwardDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *EventLogForwardDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
