// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"spkvpenergy/ocapi/models"
)

// NewGetCompanyEventsParams creates a new GetCompanyEventsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCompanyEventsParams() *GetCompanyEventsParams {
	return &GetCompanyEventsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCompanyEventsParamsWithTimeout creates a new GetCompanyEventsParams object
// with the ability to set a timeout on a request.
func NewGetCompanyEventsParamsWithTimeout(timeout time.Duration) *GetCompanyEventsParams {
	return &GetCompanyEventsParams{
		timeout: timeout,
	}
}

// NewGetCompanyEventsParamsWithContext creates a new GetCompanyEventsParams object
// with the ability to set a context for a request.
func NewGetCompanyEventsParamsWithContext(ctx context.Context) *GetCompanyEventsParams {
	return &GetCompanyEventsParams{
		Context: ctx,
	}
}

// NewGetCompanyEventsParamsWithHTTPClient creates a new GetCompanyEventsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCompanyEventsParamsWithHTTPClient(client *http.Client) *GetCompanyEventsParams {
	return &GetCompanyEventsParams{
		HTTPClient: client,
	}
}

/* GetCompanyEventsParams contains all the parameters to send to the API endpoint
   for the get company events operation.

   Typically these are written to a http.Request.
*/
type GetCompanyEventsParams struct {

	// Body.
	Body *models.GetCompanyEventsReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get company events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCompanyEventsParams) WithDefaults() *GetCompanyEventsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get company events params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCompanyEventsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get company events params
func (o *GetCompanyEventsParams) WithTimeout(timeout time.Duration) *GetCompanyEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get company events params
func (o *GetCompanyEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get company events params
func (o *GetCompanyEventsParams) WithContext(ctx context.Context) *GetCompanyEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get company events params
func (o *GetCompanyEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get company events params
func (o *GetCompanyEventsParams) WithHTTPClient(client *http.Client) *GetCompanyEventsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get company events params
func (o *GetCompanyEventsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the get company events params
func (o *GetCompanyEventsParams) WithBody(body *models.GetCompanyEventsReq) *GetCompanyEventsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the get company events params
func (o *GetCompanyEventsParams) SetBody(body *models.GetCompanyEventsReq) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GetCompanyEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
