// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"spkvpenergy/ocapi/models"
)

// GetCompanyEventsReader is a Reader for the GetCompanyEvents structure.
type GetCompanyEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCompanyEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCompanyEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetCompanyEventsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCompanyEventsOK creates a GetCompanyEventsOK with default headers values
func NewGetCompanyEventsOK() *GetCompanyEventsOK {
	return &GetCompanyEventsOK{}
}

/* GetCompanyEventsOK describes a response with status code 200, with default header values.

Events for all company devices
*/
type GetCompanyEventsOK struct {
	Payload models.DeviceEvents
}

func (o *GetCompanyEventsOK) Error() string {
	return fmt.Sprintf("[GET /company/events-list][%d] getCompanyEventsOK  %+v", 200, o.Payload)
}
func (o *GetCompanyEventsOK) GetPayload() models.DeviceEvents {
	return o.Payload
}

func (o *GetCompanyEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCompanyEventsDefault creates a GetCompanyEventsDefault with default headers values
func NewGetCompanyEventsDefault(code int) *GetCompanyEventsDefault {
	return &GetCompanyEventsDefault{
		_statusCode: code,
	}
}

/* GetCompanyEventsDefault describes a response with status code -1, with default header values.

unexpected error
*/
type GetCompanyEventsDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the get company events default response
func (o *GetCompanyEventsDefault) Code() int {
	return o._statusCode
}

func (o *GetCompanyEventsDefault) Error() string {
	return fmt.Sprintf("[GET /company/events-list][%d] getCompanyEvents default  %+v", o._statusCode, o.Payload)
}
func (o *GetCompanyEventsDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *GetCompanyEventsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
