// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"spkvpenergy/ocapi/models"
)

// GetLastParametersDataReader is a Reader for the GetLastParametersData structure.
type GetLastParametersDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLastParametersDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLastParametersDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetLastParametersDataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetLastParametersDataOK creates a GetLastParametersDataOK with default headers values
func NewGetLastParametersDataOK() *GetLastParametersDataOK {
	return &GetLastParametersDataOK{}
}

/* GetLastParametersDataOK describes a response with status code 200, with default header values.

Parameters last data from storage
*/
type GetLastParametersDataOK struct {
	Payload models.LastData
}

func (o *GetLastParametersDataOK) Error() string {
	return fmt.Sprintf("[GET /parameters/last-data][%d] getLastParametersDataOK  %+v", 200, o.Payload)
}
func (o *GetLastParametersDataOK) GetPayload() models.LastData {
	return o.Payload
}

func (o *GetLastParametersDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLastParametersDataDefault creates a GetLastParametersDataDefault with default headers values
func NewGetLastParametersDataDefault(code int) *GetLastParametersDataDefault {
	return &GetLastParametersDataDefault{
		_statusCode: code,
	}
}

/* GetLastParametersDataDefault describes a response with status code -1, with default header values.

unexpected error
*/
type GetLastParametersDataDefault struct {
	_statusCode int

	Payload *models.ErrorModel
}

// Code gets the status code for the get last parameters data default response
func (o *GetLastParametersDataDefault) Code() int {
	return o._statusCode
}

func (o *GetLastParametersDataDefault) Error() string {
	return fmt.Sprintf("[GET /parameters/last-data][%d] getLastParametersData default  %+v", o._statusCode, o.Payload)
}
func (o *GetLastParametersDataDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *GetLastParametersDataDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
